### ISSUE TITLE
not writable in local database

### ISSUE THREAD

**Issue by yiliyl** [intel/workload-collocation-agent#129]
https://github.com/intel/workload-collocation-agent/blob/7e0b939cf3a1b2f1a34158290c331f8195118297/wca/databases.py#L65-L69

I think it should be

```py
with open(full_path,'w') as f:
```

**Comment by yiliyl** [comment]
@Creatone 
I think we should check if the directory exists, then create
https://github.com/intel/workload-collocation-agent/blob/7e0b939cf3a1b2f1a34158290c331f8195118297/wca/databases.py#L62-L63

btw, we shoud ensure the path before set key-value:
```
# Ensure a path, create if necessary, otherwise there will be no-node error for zookeeper
self._client.ensure_path(full_path)
```
https://github.com/intel/workload-collocation-agent/blob/7e0b939cf3a1b2f1a34158290c331f8195118297/wca/databases.py#L93-L94

**Comment by Creatone** [comment]
@yiliyl Thank you for writing this issue. There are more issues because I thought that Local and Zookeper abstraction was tested. I'll fix it today.

**Comment by Creatone** [comment]
#131
