### ISSUE TITLE
AttributeError: 'SSL' object has no attribute 'get_certs'

### ISSUE THREAD

**Issue by yiliyl** [intel/workload-collocation-agent#158]
may be you want to use 'get_client_certs'

https://github.com/intel/workload-collocation-agent/blob/52730131feebb61d310e8463ee60bb1ef353d3c4/wca/databases.py#L197-L202

https://github.com/intel/workload-collocation-agent/blob/52730131feebb61d310e8463ee60bb1ef353d3c4/wca/security.py#L138-L144

@ppalucki  please fix it

**Comment by ppalucki** [comment]
fixed in #161 and backported to 1.0.x branch
