### ISSUE TITLE
TypeError: isinstance() arg 2 must be a type or tuple of types

### ISSUE THREAD

**Issue by yiliyl** [intel/workload-collocation-agent#159]
TypeError: isinstance() arg 2 must be a type or tuple of types

Path is a function here

https://github.com/intel/workload-collocation-agent/blob/52730131feebb61d310e8463ee60bb1ef353d3c4/wca/databases.py#L120-L123

**Comment by yiliyl** [comment]
@ppalucki

**Comment by ppalucki** [comment]
fixed in #161 and backported to 1.0.x branch
