### ISSUE TITLE
etcd connection error: `urljoin` not working as expected

### ISSUE THREAD

**Issue by yiliyl** [intel/workload-collocation-agent#160]
https://github.com/intel/workload-collocation-agent/blob/52730131feebb61d310e8463ee60bb1ef353d3c4/wca/databases.py#L194-L196

for example
```
api_path = 'http://x.x.x.x.2379/v3alpha'
url = '/kv/put'
```
after ```urljoin(api_url, url)```

return ```http://x.x.x.x.2379/kv/put```

not what we expected like ```http://x.x.x.x.2379/v3alpha/kv/put```

**Comment by yiliyl** [comment]
@ppalucki

**Comment by ppalucki** [comment]
fixed in #161 and backported to 1.0.x branch
