### ISSUE TITLE
Missing content in passed url.

### ISSUE THREAD

**Issue by Creatone** [intel/workload-collocation-agent#248]
https://github.com/intel/workload-collocation-agent/blob/c792acb7c6ab73eea511849072c9d7eeefa24122/wca/resctrl_allocations.py#L290-L294

There is `"This file does not exist"` error in passed url.

**Comment by ppalucki** [comment]
The proper link is: https://github.com/torvalds/linux/blob/9cf6b756cdf2cd38b8b0dac2567f7c6daf5e79d5/arch/x86/kernel/cpu/resctrl/ctrlmondata.c#L254

**Comment by Creatone** [comment]
Fixed in #250
