### ISSUE TITLE
Agent stops collecting metrics on task when one of the containers in a task restarts

### ISSUE THREAD

**Issue by mmucek95** [intel/workload-collocation-agent#374]
Agent stops collecting metrics on a task that has more than one container and one of them restarts. Agent throws errors and does not acknowledge the presence of the newly started container.
It won't happen every time container restarts. 

Steps to reproduce the behaviour:
1. Start workload collocation agent
2. Start Kubernetes pod with two containers. Configure one of them to sleep for a minute and then restart.
3. Observe the workload collocation agent's logs to see the error.

When one of the containers restarts, the agent should be able to detect the new one and not try to read metrics from the previous one.

![Screenshot from 2019-12-20 17-15-04](https://user-images.githubusercontent.com/27088196/71268739-f5b5ae80-234d-11ea-8ec5-7aa8ce22056a.png)

 - WCA Version as reported by ``./dist/wca.pex --version``

**Comment by Creatone** [comment]
#396 should fix it!

**Comment by Creatone** [comment]
#397 similar
